export const ASSET_MANIFEST_VERSION = 1 as const;

export type AssetLicense = "project-original" | "CC0" | "MakeHuman-CC0";
export type AssetLod = "lod0" | "lod1" | "lod2" | "shared";

export interface AssetManifestEntry {
  id: string;
  kind: "model" | "texture" | "audio" | "font";
  uri: string;
  bytes: number | null;
  lod: AssetLod;
  triangles?: number;
  license: AssetLicense;
  source: string;
  offline: "precache" | "runtime";
}

export const ASSET_MANIFEST: AssetManifestEntry[] = [
  { id: "display-font", kind: "font", uri: "/fonts/BarlowCondensed-Bold.ttf", bytes: null, lod: "shared", license: "project-original", source: "Bundled with project", offline: "precache" },
  { id: "pitch-procedural", kind: "texture", uri: "procedural:grass", bytes: 0, lod: "shared", license: "project-original", source: "Generated by the game", offline: "runtime" },
  { id: "player-procedural-lod0", kind: "model", uri: "procedural:player/lod0", bytes: 0, lod: "lod0", triangles: 24000, license: "project-original", source: "Procedural player rig", offline: "runtime" },
  { id: "player-procedural-lod1", kind: "model", uri: "procedural:player/lod1", bytes: 0, lod: "lod1", triangles: 6000, license: "project-original", source: "Procedural player rig", offline: "runtime" },
  { id: "player-procedural-lod2", kind: "model", uri: "procedural:player/lod2", bytes: 0, lod: "lod2", triangles: 1000, license: "project-original", source: "Procedural player rig", offline: "runtime" }
];
