export const ASSET_MANIFEST_VERSION = 1 as const;

export type AssetLicense = "project-original" | "CC0" | "MakeHuman-CC0";
export type AssetLod = "lod0" | "lod1" | "lod2" | "shared";

export interface AssetManifestEntry {
  id: string;
  kind: "model" | "texture" | "audio" | "font";
  uri: string;
  bytes: number | null;
  lod: AssetLod;
  triangles?: number;
  license: AssetLicense;
  source: string;
  offline: "precache" | "runtime";
}

import grassAsset from "@/assets/textures/grass_albedo.ktx2.asset.json";
import grassNormalAsset from "@/assets/textures/grass_normal.ktx2.asset.json";
import concreteAsset from "@/assets/textures/concrete_albedo.ktx2.asset.json";
import netAsset from "@/assets/textures/net_mask.ktx2.asset.json";

export const ASSET_MANIFEST: AssetManifestEntry[] = [
  { id: "display-font", kind: "font", uri: "/fonts/BarlowCondensed-Bold.ttf", bytes: null, lod: "shared", license: "project-original", source: "Bundled with project", offline: "precache" },
  { id: "pitch-procedural", kind: "texture", uri: "procedural:grass", bytes: 0, lod: "shared", license: "project-original", source: "Generated by the game", offline: "runtime" },
  { id: "pitch-ktx2", kind: "texture", uri: grassAsset.url, bytes: grassAsset.size, lod: "lod0", license: "project-original", source: "Procedural grass converted to KTX2 ETC1S", offline: "runtime" },
  { id: "pitch-normal-ktx2", kind: "texture", uri: grassNormalAsset.url, bytes: grassNormalAsset.size, lod: "lod0", license: "project-original", source: "Procedural grass normal converted to KTX2 ETC1S", offline: "runtime" },
  { id: "stadium-concrete-ktx2", kind: "texture", uri: concreteAsset.url, bytes: concreteAsset.size, lod: "lod0", license: "project-original", source: "Procedural concrete converted to KTX2 ETC1S", offline: "runtime" },
  { id: "goal-net-ktx2", kind: "texture", uri: netAsset.url, bytes: netAsset.size, lod: "lod0", license: "project-original", source: "Procedural net mask converted to KTX2 ETC1S", offline: "runtime" },
  { id: "player-procedural-lod0", kind: "model", uri: "procedural:player/lod0", bytes: 0, lod: "lod0", triangles: 24000, license: "project-original", source: "Procedural player rig", offline: "runtime" },
  { id: "player-procedural-lod1", kind: "model", uri: "procedural:player/lod1", bytes: 0, lod: "lod1", triangles: 6000, license: "project-original", source: "Procedural player rig", offline: "runtime" },
  { id: "player-procedural-lod2", kind: "model", uri: "procedural:player/lod2", bytes: 0, lod: "lod2", triangles: 1000, license: "project-original", source: "Procedural player rig", offline: "runtime" }
];
