/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BoardRouteImport } from './routes/board'
import { Route as BrasileiraoRouteImport } from './routes/brasileirao'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ClubRouteImport } from './routes/club'
import { Route as ComoSerTecnicoDeFutebolRouteImport } from './routes/como-ser-tecnico-de-futebol'
import { Route as CriadorRouteImport } from './routes/criador'
import { Route as CupRouteImport } from './routes/cup'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DicasDeGestaoRouteImport } from './routes/dicas-de-gestao'
import { Route as FinancesRouteImport } from './routes/finances'
import { Route as GuiasRouteImport } from './routes/guias'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as JogoDeManagerDeFutebolRouteImport } from './routes/jogo-de-manager-de-futebol'
import { Route as LeagueRouteImport } from './routes/league'
import { Route as LigasDeFutebolRouteImport } from './routes/ligas-de-futebol'
import { Route as MatchRouteImport } from './routes/match'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MercadoDeTransferenciasRouteImport } from './routes/mercado-de-transferencias'
import { Route as NewRouteImport } from './routes/new'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PartidaRapidaRouteImport } from './routes/partida-rapida'
import { Route as PerguntasFrequentesRouteImport } from './routes/perguntas-frequentes'
import { Route as ScoutingRouteImport } from './routes/scouting'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SoccerManagerOnlineRouteImport } from './routes/soccer-manager-online'
import { Route as SquadRouteImport } from './routes/squad'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as TacticsRouteImport } from './routes/tactics'
import { Route as TaticasEFormacoesRouteImport } from './routes/taticas-e-formacoes'
import { Route as TemporadaAutomaticaRouteImport } from './routes/temporada-automatica'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicSyncFootballRouteImport } from './routes/api/public/sync-football'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const BrasileiraoRoute = BrasileiraoRouteImport.update({
  id: '/brasileirao',
  path: '/brasileirao',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRoute = ClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoSerTecnicoDeFutebolRoute = ComoSerTecnicoDeFutebolRouteImport.update({
  id: '/como-ser-tecnico-de-futebol',
  path: '/como-ser-tecnico-de-futebol',
  getParentRoute: () => rootRouteImport,
} as any)
const CriadorRoute = CriadorRouteImport.update({
  id: '/criador',
  path: '/criador',
  getParentRoute: () => rootRouteImport,
} as any)
const CupRoute = CupRouteImport.update({
  id: '/cup',
  path: '/cup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DicasDeGestaoRoute = DicasDeGestaoRouteImport.update({
  id: '/dicas-de-gestao',
  path: '/dicas-de-gestao',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancesRoute = FinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiasRoute = GuiasRouteImport.update({
  id: '/guias',
  path: '/guias',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const JogoDeManagerDeFutebolRoute = JogoDeManagerDeFutebolRouteImport.update({
  id: '/jogo-de-manager-de-futebol',
  path: '/jogo-de-manager-de-futebol',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueRoute = LeagueRouteImport.update({
  id: '/league',
  path: '/league',
  getParentRoute: () => rootRouteImport,
} as any)
const LigasDeFutebolRoute = LigasDeFutebolRouteImport.update({
  id: '/ligas-de-futebol',
  path: '/ligas-de-futebol',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoDeTransferenciasRoute = MercadoDeTransferenciasRouteImport.update({
  id: '/mercado-de-transferencias',
  path: '/mercado-de-transferencias',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidaRapidaRoute = PartidaRapidaRouteImport.update({
  id: '/partida-rapida',
  path: '/partida-rapida',
  getParentRoute: () => rootRouteImport,
} as any)
const PerguntasFrequentesRoute = PerguntasFrequentesRouteImport.update({
  id: '/perguntas-frequentes',
  path: '/perguntas-frequentes',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutingRoute = ScoutingRouteImport.update({
  id: '/scouting',
  path: '/scouting',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SoccerManagerOnlineRoute = SoccerManagerOnlineRouteImport.update({
  id: '/soccer-manager-online',
  path: '/soccer-manager-online',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadRoute = SquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TacticsRoute = TacticsRouteImport.update({
  id: '/tactics',
  path: '/tactics',
  getParentRoute: () => rootRouteImport,
} as any)
const TaticasEFormacoesRoute = TaticasEFormacoesRouteImport.update({
  id: '/taticas-e-formacoes',
  path: '/taticas-e-formacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const TemporadaAutomaticaRoute = TemporadaAutomaticaRouteImport.update({
  id: '/temporada-automatica',
  path: '/temporada-automatica',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncFootballRoute = ApiPublicSyncFootballRouteImport.update({
  id: '/api/public/sync-football',
  path: '/api/public/sync-football',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/board': typeof BoardRoute
  '/brasileirao': typeof BrasileiraoRoute
  '/cadastro': typeof CadastroRoute
  '/club': typeof ClubRoute
  '/como-ser-tecnico-de-futebol': typeof ComoSerTecnicoDeFutebolRoute
  '/criador': typeof CriadorRoute
  '/cup': typeof CupRoute
  '/dashboard': typeof DashboardRoute
  '/dicas-de-gestao': typeof DicasDeGestaoRoute
  '/finances': typeof FinancesRoute
  '/guias': typeof GuiasRoute
  '/history': typeof HistoryRoute
  '/jogo-de-manager-de-futebol': typeof JogoDeManagerDeFutebolRoute
  '/league': typeof LeagueRoute
  '/ligas-de-futebol': typeof LigasDeFutebolRoute
  '/match': typeof MatchRoute
  '/mcp': typeof McpRoute
  '/mercado-de-transferencias': typeof MercadoDeTransferenciasRoute
  '/new': typeof NewRoute
  '/news': typeof NewsRoute
  '/partida-rapida': typeof PartidaRapidaRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/scouting': typeof ScoutingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soccer-manager-online': typeof SoccerManagerOnlineRoute
  '/squad': typeof SquadRoute
  '/stats': typeof StatsRoute
  '/tactics': typeof TacticsRoute
  '/taticas-e-formacoes': typeof TaticasEFormacoesRoute
  '/temporada-automatica': typeof TemporadaAutomaticaRoute
  '/training': typeof TrainingRoute
  '/transfers': typeof TransfersRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/sync-football': typeof ApiPublicSyncFootballRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/board': typeof BoardRoute
  '/brasileirao': typeof BrasileiraoRoute
  '/cadastro': typeof CadastroRoute
  '/club': typeof ClubRoute
  '/como-ser-tecnico-de-futebol': typeof ComoSerTecnicoDeFutebolRoute
  '/criador': typeof CriadorRoute
  '/cup': typeof CupRoute
  '/dashboard': typeof DashboardRoute
  '/dicas-de-gestao': typeof DicasDeGestaoRoute
  '/finances': typeof FinancesRoute
  '/guias': typeof GuiasRoute
  '/history': typeof HistoryRoute
  '/jogo-de-manager-de-futebol': typeof JogoDeManagerDeFutebolRoute
  '/league': typeof LeagueRoute
  '/ligas-de-futebol': typeof LigasDeFutebolRoute
  '/match': typeof MatchRoute
  '/mcp': typeof McpRoute
  '/mercado-de-transferencias': typeof MercadoDeTransferenciasRoute
  '/new': typeof NewRoute
  '/news': typeof NewsRoute
  '/partida-rapida': typeof PartidaRapidaRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/scouting': typeof ScoutingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soccer-manager-online': typeof SoccerManagerOnlineRoute
  '/squad': typeof SquadRoute
  '/stats': typeof StatsRoute
  '/tactics': typeof TacticsRoute
  '/taticas-e-formacoes': typeof TaticasEFormacoesRoute
  '/temporada-automatica': typeof TemporadaAutomaticaRoute
  '/training': typeof TrainingRoute
  '/transfers': typeof TransfersRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/sync-football': typeof ApiPublicSyncFootballRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/board': typeof BoardRoute
  '/brasileirao': typeof BrasileiraoRoute
  '/cadastro': typeof CadastroRoute
  '/club': typeof ClubRoute
  '/como-ser-tecnico-de-futebol': typeof ComoSerTecnicoDeFutebolRoute
  '/criador': typeof CriadorRoute
  '/cup': typeof CupRoute
  '/dashboard': typeof DashboardRoute
  '/dicas-de-gestao': typeof DicasDeGestaoRoute
  '/finances': typeof FinancesRoute
  '/guias': typeof GuiasRoute
  '/history': typeof HistoryRoute
  '/jogo-de-manager-de-futebol': typeof JogoDeManagerDeFutebolRoute
  '/league': typeof LeagueRoute
  '/ligas-de-futebol': typeof LigasDeFutebolRoute
  '/match': typeof MatchRoute
  '/mcp': typeof McpRoute
  '/mercado-de-transferencias': typeof MercadoDeTransferenciasRoute
  '/new': typeof NewRoute
  '/news': typeof NewsRoute
  '/partida-rapida': typeof PartidaRapidaRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/scouting': typeof ScoutingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soccer-manager-online': typeof SoccerManagerOnlineRoute
  '/squad': typeof SquadRoute
  '/stats': typeof StatsRoute
  '/tactics': typeof TacticsRoute
  '/taticas-e-formacoes': typeof TaticasEFormacoesRoute
  '/temporada-automatica': typeof TemporadaAutomaticaRoute
  '/training': typeof TrainingRoute
  '/transfers': typeof TransfersRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/sync-football': typeof ApiPublicSyncFootballRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/board'
    | '/brasileirao'
    | '/cadastro'
    | '/club'
    | '/como-ser-tecnico-de-futebol'
    | '/criador'
    | '/cup'
    | '/dashboard'
    | '/dicas-de-gestao'
    | '/finances'
    | '/guias'
    | '/history'
    | '/jogo-de-manager-de-futebol'
    | '/league'
    | '/ligas-de-futebol'
    | '/match'
    | '/mcp'
    | '/mercado-de-transferencias'
    | '/new'
    | '/news'
    | '/partida-rapida'
    | '/perguntas-frequentes'
    | '/scouting'
    | '/sitemap.xml'
    | '/soccer-manager-online'
    | '/squad'
    | '/stats'
    | '/tactics'
    | '/taticas-e-formacoes'
    | '/temporada-automatica'
    | '/training'
    | '/transfers'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/api/public/sync-football'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/board'
    | '/brasileirao'
    | '/cadastro'
    | '/club'
    | '/como-ser-tecnico-de-futebol'
    | '/criador'
    | '/cup'
    | '/dashboard'
    | '/dicas-de-gestao'
    | '/finances'
    | '/guias'
    | '/history'
    | '/jogo-de-manager-de-futebol'
    | '/league'
    | '/ligas-de-futebol'
    | '/match'
    | '/mcp'
    | '/mercado-de-transferencias'
    | '/new'
    | '/news'
    | '/partida-rapida'
    | '/perguntas-frequentes'
    | '/scouting'
    | '/sitemap.xml'
    | '/soccer-manager-online'
    | '/squad'
    | '/stats'
    | '/tactics'
    | '/taticas-e-formacoes'
    | '/temporada-automatica'
    | '/training'
    | '/transfers'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/api/public/sync-football'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/board'
    | '/brasileirao'
    | '/cadastro'
    | '/club'
    | '/como-ser-tecnico-de-futebol'
    | '/criador'
    | '/cup'
    | '/dashboard'
    | '/dicas-de-gestao'
    | '/finances'
    | '/guias'
    | '/history'
    | '/jogo-de-manager-de-futebol'
    | '/league'
    | '/ligas-de-futebol'
    | '/match'
    | '/mcp'
    | '/mercado-de-transferencias'
    | '/new'
    | '/news'
    | '/partida-rapida'
    | '/perguntas-frequentes'
    | '/scouting'
    | '/sitemap.xml'
    | '/soccer-manager-online'
    | '/squad'
    | '/stats'
    | '/tactics'
    | '/taticas-e-formacoes'
    | '/temporada-automatica'
    | '/training'
    | '/transfers'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/api/public/sync-football'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BoardRoute: typeof BoardRoute
  BrasileiraoRoute: typeof BrasileiraoRoute
  CadastroRoute: typeof CadastroRoute
  ClubRoute: typeof ClubRoute
  ComoSerTecnicoDeFutebolRoute: typeof ComoSerTecnicoDeFutebolRoute
  CriadorRoute: typeof CriadorRoute
  CupRoute: typeof CupRoute
  DashboardRoute: typeof DashboardRoute
  DicasDeGestaoRoute: typeof DicasDeGestaoRoute
  FinancesRoute: typeof FinancesRoute
  GuiasRoute: typeof GuiasRoute
  HistoryRoute: typeof HistoryRoute
  JogoDeManagerDeFutebolRoute: typeof JogoDeManagerDeFutebolRoute
  LeagueRoute: typeof LeagueRoute
  LigasDeFutebolRoute: typeof LigasDeFutebolRoute
  MatchRoute: typeof MatchRoute
  McpRoute: typeof McpRoute
  MercadoDeTransferenciasRoute: typeof MercadoDeTransferenciasRoute
  NewRoute: typeof NewRoute
  NewsRoute: typeof NewsRoute
  PartidaRapidaRoute: typeof PartidaRapidaRoute
  PerguntasFrequentesRoute: typeof PerguntasFrequentesRoute
  ScoutingRoute: typeof ScoutingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SoccerManagerOnlineRoute: typeof SoccerManagerOnlineRoute
  SquadRoute: typeof SquadRoute
  StatsRoute: typeof StatsRoute
  TacticsRoute: typeof TacticsRoute
  TaticasEFormacoesRoute: typeof TaticasEFormacoesRoute
  TemporadaAutomaticaRoute: typeof TemporadaAutomaticaRoute
  TrainingRoute: typeof TrainingRoute
  TransfersRoute: typeof TransfersRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiPublicSyncFootballRoute: typeof ApiPublicSyncFootballRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brasileirao': {
      id: '/brasileirao'
      path: '/brasileirao'
      fullPath: '/brasileirao'
      preLoaderRoute: typeof BrasileiraoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club': {
      id: '/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-ser-tecnico-de-futebol': {
      id: '/como-ser-tecnico-de-futebol'
      path: '/como-ser-tecnico-de-futebol'
      fullPath: '/como-ser-tecnico-de-futebol'
      preLoaderRoute: typeof ComoSerTecnicoDeFutebolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criador': {
      id: '/criador'
      path: '/criador'
      fullPath: '/criador'
      preLoaderRoute: typeof CriadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cup': {
      id: '/cup'
      path: '/cup'
      fullPath: '/cup'
      preLoaderRoute: typeof CupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dicas-de-gestao': {
      id: '/dicas-de-gestao'
      path: '/dicas-de-gestao'
      fullPath: '/dicas-de-gestao'
      preLoaderRoute: typeof DicasDeGestaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finances': {
      id: '/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof FinancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias': {
      id: '/guias'
      path: '/guias'
      fullPath: '/guias'
      preLoaderRoute: typeof GuiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogo-de-manager-de-futebol': {
      id: '/jogo-de-manager-de-futebol'
      path: '/jogo-de-manager-de-futebol'
      fullPath: '/jogo-de-manager-de-futebol'
      preLoaderRoute: typeof JogoDeManagerDeFutebolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league': {
      id: '/league'
      path: '/league'
      fullPath: '/league'
      preLoaderRoute: typeof LeagueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ligas-de-futebol': {
      id: '/ligas-de-futebol'
      path: '/ligas-de-futebol'
      fullPath: '/ligas-de-futebol'
      preLoaderRoute: typeof LigasDeFutebolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado-de-transferencias': {
      id: '/mercado-de-transferencias'
      path: '/mercado-de-transferencias'
      fullPath: '/mercado-de-transferencias'
      preLoaderRoute: typeof MercadoDeTransferenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partida-rapida': {
      id: '/partida-rapida'
      path: '/partida-rapida'
      fullPath: '/partida-rapida'
      preLoaderRoute: typeof PartidaRapidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perguntas-frequentes': {
      id: '/perguntas-frequentes'
      path: '/perguntas-frequentes'
      fullPath: '/perguntas-frequentes'
      preLoaderRoute: typeof PerguntasFrequentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scouting': {
      id: '/scouting'
      path: '/scouting'
      fullPath: '/scouting'
      preLoaderRoute: typeof ScoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soccer-manager-online': {
      id: '/soccer-manager-online'
      path: '/soccer-manager-online'
      fullPath: '/soccer-manager-online'
      preLoaderRoute: typeof SoccerManagerOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squad': {
      id: '/squad'
      path: '/squad'
      fullPath: '/squad'
      preLoaderRoute: typeof SquadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tactics': {
      id: '/tactics'
      path: '/tactics'
      fullPath: '/tactics'
      preLoaderRoute: typeof TacticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taticas-e-formacoes': {
      id: '/taticas-e-formacoes'
      path: '/taticas-e-formacoes'
      fullPath: '/taticas-e-formacoes'
      preLoaderRoute: typeof TaticasEFormacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temporada-automatica': {
      id: '/temporada-automatica'
      path: '/temporada-automatica'
      fullPath: '/temporada-automatica'
      preLoaderRoute: typeof TemporadaAutomaticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-football': {
      id: '/api/public/sync-football'
      path: '/api/public/sync-football'
      fullPath: '/api/public/sync-football'
      preLoaderRoute: typeof ApiPublicSyncFootballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BoardRoute: BoardRoute,
  BrasileiraoRoute: BrasileiraoRoute,
  CadastroRoute: CadastroRoute,
  ClubRoute: ClubRoute,
  ComoSerTecnicoDeFutebolRoute: ComoSerTecnicoDeFutebolRoute,
  CriadorRoute: CriadorRoute,
  CupRoute: CupRoute,
  DashboardRoute: DashboardRoute,
  DicasDeGestaoRoute: DicasDeGestaoRoute,
  FinancesRoute: FinancesRoute,
  GuiasRoute: GuiasRoute,
  HistoryRoute: HistoryRoute,
  JogoDeManagerDeFutebolRoute: JogoDeManagerDeFutebolRoute,
  LeagueRoute: LeagueRoute,
  LigasDeFutebolRoute: LigasDeFutebolRoute,
  MatchRoute: MatchRoute,
  McpRoute: McpRoute,
  MercadoDeTransferenciasRoute: MercadoDeTransferenciasRoute,
  NewRoute: NewRoute,
  NewsRoute: NewsRoute,
  PartidaRapidaRoute: PartidaRapidaRoute,
  PerguntasFrequentesRoute: PerguntasFrequentesRoute,
  ScoutingRoute: ScoutingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SoccerManagerOnlineRoute: SoccerManagerOnlineRoute,
  SquadRoute: SquadRoute,
  StatsRoute: StatsRoute,
  TacticsRoute: TacticsRoute,
  TaticasEFormacoesRoute: TaticasEFormacoesRoute,
  TemporadaAutomaticaRoute: TemporadaAutomaticaRoute,
  TrainingRoute: TrainingRoute,
  TransfersRoute: TransfersRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiPublicSyncFootballRoute: ApiPublicSyncFootballRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
